#!/bin/sh

set -ex
cd -P -- "$(dirname -- "$(realpath -- "$0")")"

_readme() {
	echo "# notes"
	echo
	echo "My notes mostly about system administration, devops, programming and business."
	echo
	echo "Inspired by [simonw/til](https://github.com/simonw/til). Currently contains $(find . -name '*.md' | wc -l) pages."
	echo
	find . -type d -not -wholename '*.git*' -not -name . | sort | while IFS= read -r dir; do
		echo "## $(echo $dir | sed 's/^\.\///')"
		echo
		find $dir -name '*.md' | while IFS= read -r file; do
			title=$(head -1 $file | sed 's/^# //')
			date=$(git log -1 --pretty="format:%as" $file)
			echo "* [$title]($file) - $date"
		done | awk '{ print $NF,$0 }' | sort -k1,1 -nr | cut -f2- -d' '
		echo
	done
}

case "$1" in
new)
	dir=$(find . -type d -not -wholename '*.git*' -not -name . | fzf --print-query | tail -1)
	tmpfile=$(mktemp /tmp/notes.XXXXXX.md)
	vim $tmpfile
	newtitle=$(head -1 $tmpfile | sed 's/^# //')
	newfilename=$(echo "$newtitle" | iconv -c -t ascii//TRANSLIT | sed -E 's/[~^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z)
	if [ -z "$newfilename" ]; then
		echo oops
		exit 1
	fi
	mkdir -p $dir
	newfile="$dir/$newfilename.md"
	mv $tmpfile $newfile
	git add $newfile
	git commit -m "add $newfile"
	;;
sync)
	git stash
	git pull -r
	_readme > README.md
	git add README.md
	git commit -m "update readme"
	git diff --cached origin/main
	git push -u origin main
	git stash pop
	;;
web)
	xdg-open https://github.com/bdeak4/notes
	;;
*)
	file=$(fzf --layout=reverse --preview "cat {}")
	oldtitle=$(head -1 $file | sed 's/^# //')
	vim $file
	newtitle=$(head -1 $file | sed 's/^# //')
	if [ "$oldtitle" != "$newtitle" ]; then
		newfilename=$(echo "$newtitle" | iconv -c -t ascii//TRANSLIT | sed -E 's/[~^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z)
		newfile="$(dirname $file)/$newfilename.md"
		mv $file $newfile
		git add $file $newfile
		git commit -m "edit $newfile"
	fi
	if [ -n "$(git diff --name-only -- $file)" ]; then
		git add $file
		git commit -m "edit $file"
	fi
esac
